### ISSUE TITLE
Jessie armhf_8 Build fails with unmet crossbuild dependencies

### ISSUE THREAD

**Issue by dkhughes** [Dovetail-Automata/mk-cross-builder#3]
When building the armhf_8 image, apt fails to resolve crossbuild-essential-armhf. I moved away from using that repo and directly installing a cross compiler for amd_64 in the container we used to build u-boot and kernels for the zynq images. See: [https://github.com/dkhughes/ubker-docker/blob/master/Dockerfile.in#L60](https://github.com/dkhughes/ubker-docker/blob/master/Dockerfile.in#L60).

I'm going to hack this into our fork to get the image building. Can you see any downside to changing to this approach in general? I figure we will have to select the proper download archive based on architecture unless you only support 64-bit docker (that's what we do with the ubker images).

**Comment by zultron** [comment]
Hi @dkhughes,

I'm having an obtuse moment here, please hold my hand.  If your question is, in this git repo, could you replace the emdebian cross-compile toolchain with the linaro toolchain, and would the wacky `gcc --sysroot` in a multistrap tree scheme still work, I would think so, yes.

The only value of this scheme over others is that it allows you to cross-compile Debian packages that can't be cross-compiled using Debian's immature `Multiarch:` scheme.  Be warned this is a major hack, both complex and unsupported, and you'll have to resolve problems on your own.  If you're not trying to compile packages, then I'd recommend staying away from this and using more traditional cross-build toolchain techniques.  If you are building packages, consider native builds (I personally love Scaleway's $5/month ARM cloud servers).

**Comment by dkhughes** [comment]
Hi @zultron,

I have some imx cuboxes that I use to run an image building process, and I do like the native build. However, for machinekit, I have been using your docker image to cross compile the packages from our CI simply for speed. The fork of machinekit I run has a couple of cnc control changes that would never make it upstream (too specialized), so we build our own packages externally as we keep in sync with upstream.

I tried building the jessie image today and it failed since it seems like the emdebian repos were updated and are maybe out of sync with their dependencies. The issue happens often enough that I changed the kernel building jessie images for the zynq (ubker in the machinekit jenkins) to a static reference of gcc (the linaro tools). I just updated the docker script generating the images locally and it seems to be building machinekit-hal fine, but of course I think it needs some more testing.

I was mostly curious if you thought it would be beneficial to update the images here for that setup instead of relying on what seems to be the inconsistent emdebian repo. I think Jessie support is still going to be needed for a couple of years building packages.

**Comment by dkhughes** [comment]
Bleh, that blew up when I got it onto the target device. 

The issue seems to be the same as always - g++/gcc are depending strictly on an unavailable version of a library that the main debian repos must have updated and emdebian tools are behind. Oh well, guess I will be building natively after all ;).

**Comment by zultron** [comment]
I read a post on IIRC the Debian cross-tools ML that the emdebian project has been abandoned.  Thanks for the heads-up about the failing dependencies.  Sounds like we're going to be in trouble if/when we need to update the MK CI Docker images.

If MK also plans to keep Jessie around, then it sounds like your updates to swap in Linaro would be very useful.  I'm going to reopen this issue, since it sounds like it really is an issue.  If you have a patch, I'd appreciate it.

**Comment by zultron** [comment]
I asked about the Jessie support timeline over in machinekit/machinekit-hal#150.

As for your project, why do you say Jessie support will be needed for so long?  Is the Zynq not supported in Stretch or something?

**Comment by dkhughes** [comment]
We have a couple hundred machines that are in the field based on jessie images and it just gives us more time to workout remote dist-upgrade. New machines are being built based on stretch images, but in the meantime I plan on continuing Jessie until debian drops updates for it (2020).

I think the issue I hit earlier was a problem with the mainline pkg-config and not using the emdebian updated one, but I didn't look into it much. Basically, I worked around it by skipping Xorg stuff, and the target didn't like the end product. I'll tinker with this more over the weekend after I get a native build back in place on one of the little cubes.

**Comment by zultron** [comment]
> Bleh, that blew up when I got it onto the target device.
> 
> The issue seems to be the same as always - g++/gcc are depending strictly on an unavailable version of a library that the main debian repos must have updated and emdebian tools are behind. Oh well, guess I will be building natively after all ;).

@dkhughes What exactly was the error you're seeing?

I copy'n'pasted your changes into the Dockerfile here, and spent a couple of hours trying to puzzle out strange linking failures where symbols clearly in `libprotobuf9.so` were reported as absent.  It finally hit on me that the compiler may need to be the same version as the one that built the library, and after switching back to the Linaro gcc v. 4, the compile succeeded.

Do you think the same fix may help you?  See the above-linked commit (which also addresses the `crossbuild-essential-armhf` package problem you raised).

**Comment by zultron** [comment]
PR #4 fixes this, so closing out the issue.  Thanks for reporting this, @dkhughes.
